# language type:
language: cpp

# compilator system:
compiler:
- clang
- gcc

# build branch requested
branches:
  only:
    - master
    - dev

# previous actions:
before_script: 
  - git submodule init
  - git submodule update

# build sequence with Lutin :
script: 
  - if [ "$CXX" == "clang++" ]; then ./build/lutin.py -cclang -mdebug -p ewol; fi
  - if [ "$CXX" == "g++" ]; then script: ./build/lutin.py -cgcc -mdebug -p ewol; fi

#send e-mail on compilation result:
notifications:
  email:
    - yui.heero@gmail.com
