# language type:
language: cpp

# compilator system:
compiler:
- clang
- gcc

# build branch requested
branches:
  only:
    - master
    - dev

# previous actions:
before_script: 
  - git submodule init
  - git submodule update

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - sudo rm /usr/bin/gcc /usr/bin/g++
  - sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
  - ln -s /usr/bin/g++-4.8 /usr/bin/g++
  - if [ "$CXX" == "clang++" ]; then wget http://llvm.org/releases/3.4.1/clang+llvm-3.4.1-x86_64-unknown-ubuntu12.04.tar.xz; fi
  - if [ "$CXX" == "clang++" ]; then tar vxJf clang+llvm-3.4.1-x86_64-unknown-ubuntu12.04.tar.xz; fi
  - if [ "$CXX" == "clang++" ]; then export PATH=$PWD/clang+llvm-3.4.1-x86_64-unknown-ubuntu12.04/bin:$PATH; fi

# build sequence with Lutin :
script: 
  - if [ "$CXX" == "clang++" ]; then ./build/lutin.py -C -P -cclang -mdebug -p ewol etktest exmltest ejsontest enettest; fi
  - if [ "$CXX" == "g++" ]; then ./build/lutin.py -C -P -cgcc -mdebug -p ewol etktest exmltest ejsontest enettest; fi

after_script:
  - if [ "$CXX" == "clang++" ]; then ./out/Linux/debug/staging/clang/etktest//usr/bin/etktest; fi
  - if [ "$CXX" == "clang++" ]; then ./out/Linux/debug/staging/clang/exmltest//usr/bin/exmltest; fi
  - if [ "$CXX" == "clang++" ]; then ./out/Linux/debug/staging/clang/ejsontest//usr/bin/ejsontest; fi
  - if [ "$CXX" == "g++" ]; then ./out/Linux/debug/staging/gcc/etktest//usr/bin/etktest; fi
  - if [ "$CXX" == "g++" ]; then ./out/Linux/debug/staging/gcc/exmltest//usr/bin/exmltest; fi
  - if [ "$CXX" == "g++" ]; then ./out/Linux/debug/staging/gcc/ejsontest//usr/bin/ejsontest; fi

#send e-mail on compilation result:
notifications:
  email:
    - yui.heero@gmail.com
