language:
  - cpp

sudo: false

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

branches:
  only:
    - master
    - dev

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

install:
  - pip install --user lutin

before_script:
  - cd ..
  - mkdir bin
  - curl https://storage.googleapis.com/git-repo-downloads/repo > bin/repo
  - chmod a+x bin/repo
  - git config --global user.email "travis@travis.com"
  - git config --global user.name "Travis"
  - git config --global color.ui "auto"
  - git config --global core.editor "vi"
  - mkdir WORKING_DIRECTORY
  - cd WORKING_DIRECTORY
  - ../bin/repo init -u https://github.com/atria-soft/manifest.git
  - ../bin/repo sync -j8
  - rm -rf atria-soft/ewol
  - cd ..
  - pwd
  - ls -l
  - if [ "$CXX" == "clang++" ]; then BUILDER=clang; else BUILDER=gcc; fi
  - if [ "$CXX" == "g++" ]; then COMPILATOR_OPTION="--compilator-version=4.9"; else COMPILATOR_OPTION=""; fi

script: 
  - lutin -C -P -c$BUILDER $COMPILATOR_OPTION -mdebug -p ewol etk-test exml-test ejson-test enet-test 0XX_customwidget 001_HelloWord
  - ./out/Linux_x86_64/debug/staging/$BUILDER/etk-test/usr/bin/etk-test
  - ./out/Linux_x86_64/debug/staging/$BUILDER/ejson-test/usr/bin/ejson-test
  - ./out/Linux_x86_64/debug/staging/$BUILDER/exml-test/usr/bin/exml-test

notifications:
  email:
    - yui.heero@gmail.com
