language:
  - cpp

sudo: false

os:
  - linux
  - osx

branches:
  only:
    - master
    - dev

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

env:
  - CONF=debug BUILDER=clang
  - CONF=debug BUILDER=gcc

matrix:
  include:
    - os: linux
      env: CONF=debug BUILDER=gcc GCOV=--gcov
    - os: linux
      env: CONF=release BUILDER=clang
    - os: linux
      env: CONF=release BUILDER=gcc
  exclude:
    - os: mingw
      env: CONF=debug BUILDER=clang

install:
  - pip install --user lutin

before_script:
  - cd ..
  - wget http://atria-soft.com/ci/coverage_send.py
  - wget http://atria-soft.com/ci/test_send.py
  - wget http://atria-soft.com/ci/warning_send.py
  - mkdir bin
  - curl https://storage.googleapis.com/git-repo-downloads/repo > bin/repo
  - chmod a+x bin/repo
  - git config --global user.email "travis@travis.com"
  - git config --global user.name "Travis"
  - git config --global color.ui "auto"
  - git config --global core.editor "vi"
  - mkdir WORKING_DIRECTORY
  - cd WORKING_DIRECTORY
  - ../bin/repo init -u https://github.com/atria-soft/manifest.git
  - ../bin/repo sync -j8
  - rm -rf atria-soft/ewol
  - cd ..
  - pwd
  - ls -l
  - if [ "$BUILDER" == "gcc" ]; then
        COMPILATOR_OPTION="--compilator-version=4.9";
    else
        COMPILATOR_OPTION="";
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        export PATH=$PATH:/Users/travis/Library/Python/2.7/bin/;
    fi

script:
  - lutin -w -j4 -C -P -c $BUILDER $COMPILATOR_OPTION -m $CONF $GCOV -p ewol-test 0XX_customwidget 001_HelloWord


notifications:
  email:
    - yui.heero@gmail.com
