# language type:
language:
- cpp
- Objective-c

# compilator system:
compiler:
- clang
- gcc

# build branch requested
branches:
  only:
    - master
    - dev

# previous actions:
before_script: 
  - git submodule init
  - git submodule update
  - if [ "$CXX" == "clang++" ]; then BUILDER=clang; else BUILDER=gcc; fi

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libstdc++-4.9-dev
  - sudo apt-get install -qq g++-4.9
  - sudo rm /usr/bin/gcc /usr/bin/g++
  - sudo ln -s /usr/bin/gcc-4.9 /usr/bin/gcc
  - sudo ln -s /usr/bin/g++-4.9 /usr/bin/g++

# build sequence with Lutin :
script: 
  - ./build/lutin.py -C -P -c$BUILDER -mdebug -p ewol etk_test exml_test ejson_test enettest
  - ./out/Linux_x86_64/debug/staging/$BUILDER/etk_test/usr/bin/etk_test
  - ./out/Linux_x86_64/debug/staging/$BUILDER/ejson_test/usr/bin/ejson_test
  - ./out/Linux_x86_64/debug/staging/$BUILDER/exml_test/usr/bin/exml_test

#send e-mail on compilation result:
notifications:
  email:
    - yui.heero@gmail.com
