# language type:
language: cpp

# compilator system:
compiler:
- clang
- gcc

# Setup different environments to test
env:
- CPP11=1

# build branch requested
branches:
  only:
    - master
    - dev

# previous actions:
before_script: 
  - git submodule init
  - git submodule update

install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [ "$CXX" == "g++" ]; then sudo apt-get update -qq; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi


# build sequence with Lutin :
script: 
  - if [ "$CXX" == "clang++" ]; then ./build/lutin.py -cclang -mdebug -p ewol; fi
  - if [ "$CXX" == "g++" ]; then ./build/lutin.py -cgcc -mdebug -p ewol; fi

#send e-mail on compilation result:
notifications:
  email:
    - yui.heero@gmail.com
