# language type:
language: cpp

# build branch requested
branches:
  only:
    - master
    - stable

# previous actions:
before_script: git submodule init
before_script: git submodule update

# build sequence with Lutin :
script: ./build/lutin.py -cclang -mdebug -p ewol
